spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=postgres
spring.datasource.password=teste
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=WARN

logging.level.org.springframework=WARN
logging.level.org.apache=WARN
logging.level.org.hibernate=WARN

logging.level.com.walletapi=INFO